---
- name: install utilities
  pacman:
    name:
      - htop
      - ncdu
      - curl
      - jq
      - httpie
      - unzip
      - usbutils
      - unclutter
      - dunst
      - slock
      - pasystray
  become: true

- name: install applications
  pacman:
    name:
      - chromium
      - evince
      - mpv
      - thunar
  become: true