---
- name: Install GUI
  pacman:
    name:
      - xorg
      - xorg-xinit
  become: true

- name: Install fonts
  pacman:
    name:
      - adobe-source-code-pro-fonts
      - noto-fonts
      - powerline-fonts
      - ttf-dejavu
      - ttf-droid
      - ttf-inconsolata
      - ttf-liberation
  become: true

- name: Install display configuration tools
  pacman:
    name:
      - arandr
      - lxrandr
  become: true

- name: Install compositor
  pacman:
    name:
      - picom
  become: true

- name: Install xclip
  pacman:
    name:
      - xclip
  become: true

- name: Install GUI themes
  pacman:
    name:
      - elementary-icon-theme
      - gnome-themes-extra
      - lxappearance
  become: true