---
- name: install i3
  yay:
    name:
      - i3-gaps
      - i3lock
      - i3status
      - dmenu

- name: create i3 configuration directory
  file:
    name: /home/{{ archlinux_username }}/.config/i3
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0755

- name: configure i3
  template:
    src: i3/config
    dest: /home/{{ archlinux_username }}/.config/i3/config
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0644

- name: create i3status configuration directory
  file:
    name: /home/{{ archlinux_username }}/.config/i3status
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0755

- name: configure i3status
  template:
    src: i3status/config
    dest: /home/{{ archlinux_username }}/.config/i3status/config
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0644