---
- name: install networking tools
  pacman:
    name:
      - dhcpcd
      - ifplugd
      - netctl
      - openvpn
      - wireguard-tools
      - wpa_supplicant
      - network-manager-applet
  become: true