---
- name: create normal user
  user:
    name: "{{ archlinux_username }}"
    create_home: true
    group: users
    groups:
      - wheel
  become: true

- name: copy dotfiles
  copy:
    src: "{{ item }}"
    dest: /home/{{ archlinux_username }}/.{{ item }}
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0600
  with_items:
    - xinitrc
  become: true
  become_user: "{{ archlinux_username }}"